In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from nltk.tokenize import word_tokenize

In [2]:
path = "/Users/chongchen/Desktop/19Fall RA/data/raw data/"
doc_review = pd.read_csv(path + 'docs_before.csv', index_col = 0)
gender = pd.read_csv(path + 'genders.csv').drop_duplicates()
doc_review = pd.merge(doc_review,gender,on='hp_id',how='inner')

In [18]:
doc_review['hasorder'] = doc_review['hasorder'].map(lambda x: str(x))

In [19]:
def no_space(x):
    a = x.split(' ')
    b = ''
    for i in a:
        if i != '':
            b = b+i
    return b
doc_review['spec_comb'] = doc_review['spec_comb'].map(lambda x:no_space(x))

Focus on Internal Medicine Doctors

In [37]:
im_data = doc_review[doc_review['spec_comb']=='InternalMedicine']

In [38]:
im_data

,hp_id,ratemds_id,order_id,hasorder,review_count,avg_help,avg_know,avg_punct,avg_staff,var_help,...,cat_otherprej,cat_restrictlicense,cat_losslicense,cem_strata_alldocs,basecat_badmed,basecat_impaired,basecat_finances,basecat_criminal,basecat_patient,gender
2,19713,127113,NaN,0,11,2.272727,2.636364,3.000000,2.000000,3.218182,...,NaN,NaN,NaN,2310,0,0,0,0,0,F
6,587845,31782,NaN,0,9,4.555556,4.555556,4.222222,2.444444,1.777778,...,NaN,NaN,NaN,2665,0,0,0,0,0,M
14,1026482,33127,NaN,0,10,4.600000,4.800000,4.800000,2.800000,1.600000,...,NaN,NaN,NaN,3824,0,0,0,0,0,F
15,356796,175423,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,NaN,NaN,NaN,5862,0,0,0,0,0,F
22,1444150,459077,NaN,0,2,5.000000,5.000000,5.000000,5.000000,0.000000,...,NaN,NaN,NaN,3734,0,0,0,0,0,M
23,1298609,754757,NaN,0,4,3.000000,3.750000,4.000000,3.500000,3.333333,...,NaN,NaN,NaN,2058,0,0,0,0,0,M
26,48453,841438,NaN,0,1,3.000000,1.000000,5.000000,4.000000,NaN,...,NaN,NaN,NaN,6835,0,0,0,0,0,M
27,1128956,1252,NaN,0,3,4.666667,4.666667,4.666667,3.333333,0.333333,...,NaN,NaN,NaN,2310,0,0,0,0,0,M
28,912294,94308,NaN,0,6,3.000000,3.333333,2.833333,1.333333,3.600000,...,NaN,NaN,NaN,2991,0,0,0,0,0,M
33,1529842,418509,NaN,0,1,3.000000,3.000000,2.000000,2.000000,NaN,...,NaN,NaN,NaN,708,0,0,0,0,0,M
37,874463,147822,NaN,0,1,5.000000,4.000000,4.000000,4.000000,NaN,...,NaN,NaN,NaN,5988,0,0,0,0,0,F
40,212783,399757,NaN,0,1,5.000000,5.000000,4.000000,4.000000,NaN,...,NaN,NaN,NaN,2665,0,0,0,0,0,M
41,945140,3323975,NaN,0,1,1.000000,2.000000,1.000000,2.000000,NaN,...,NaN,NaN,NaN,6282,0,0,0,0,0,M
52,406301,162169,2037974.0,1,1,1.000000,2.000000,3.000000,2.000000,NaN,...,1.0,0.0,0.0,129,0,0,0,0,0,M
58,411960,1151070,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,NaN,NaN,NaN,3360,0,0,0,0,0,M
67,1525567,168134,NaN,0,1,1.000000,4.000000,4.000000,1.000000,NaN,...,NaN,NaN,NaN,8073,0,0,0,0,0,M
68,942069,18484,NaN,0,4,4.000000,4.250000,4.500000,1.250000,4.000000,...,NaN,NaN,NaN,4522,0,0,0,0,0,M
71,1215516,438858,NaN,0,4,2.250000,3.250000,3.500000,3.500000,3.583333,...,NaN,NaN,NaN,10021,0,0,0,0,0,M
75,1473699,123294,NaN,0,1,5.000000,5.000000,4.000000,4.000000,NaN,...,NaN,NaN,NaN,3322,0,0,0,0,0,M
84,1327850,21399,NaN,0,3,5.000000,5.000000,4.000000,1.666667,0.000000,...,NaN,NaN,NaN,311,0,0,0,0,0,F
85,1520937,165925,NaN,0,4,4.000000,4.000000,4.000000,4.000000,4.000000,...,NaN,NaN,NaN,4676,0,0,0,0,0,M
88,1054179,2626043,NaN,0,1,1.000000,1.000000,3.000000,1.000000,NaN,...,NaN,NaN,NaN,6212,0,0,0,0,0,M
91,904721,865724,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,NaN,NaN,NaN,6009,0,0,0,0,0,M
94,275305,175595,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,NaN,NaN,NaN,2823,0,0,0,0,0,M
95,1488908,3258507,NaN,0,1,2.000000,2.000000,1.000000,3.000000,NaN,...,NaN,NaN,NaN,4522,0,0,0,0,0,F
109,1608047,189982,NaN,0,1,5.000000,5.000000,5.000000,3.000000,NaN,...,NaN,NaN,NaN,2711,0,0,0,0,0,F
118,269347,18985,NaN,0,7,3.000000,3.571429,3.714286,1.714286,4.000000,...,NaN,NaN,NaN,3606,0,0,0,0,0,M
120,827768,3262839,NaN,0,1,1.000000,2.000000,3.000000,4.000000,NaN,...,NaN,NaN,NaN,3322,0,0,0,0,0,M
122,890406,121100,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,NaN,NaN,NaN,2368,0,0,0,0,0,F
123,1371705,124510,NaN,0,1,5.000000,5.000000,5.000000,NaN,NaN,...,NaN,NaN,NaN,1741,0,0,0,0,0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134857,1195114,247510,NaN,0,1,1.000000,1.000000,1.000000,1.000000,NaN,...,NaN,NaN,NaN,5536,0,0,0,0,0,M
134862,511759,171216,NaN,0,2,3.000000,3.000000,3.000000,3.000000,8.000000,...,NaN,NaN,NaN,2443,0,0,0,0,0,M
134869,495256,142884,NaN,0,4,4.000000,4.500000,3.750000,3.500000,4.000000,...,NaN,NaN,NaN,1958,0,0,0,0,0,M
134870,401038,643557,NaN,0,3,5.000000,5.000000,4.666667,5.000000,0.000000,...,NaN,NaN,NaN,2405,0,0,0,0,0,F
134880,88457,111288,NaN,0,2,3.000000,3.000000,4.000000,4.000000,8.000000,...,NaN,NaN,NaN,3606,0,0,0,0,0,M
134882,1012083,208232,NaN,0,2,3.000000,3.000000,2.500000,2.500000,8.000000,...,NaN,NaN,NaN,9247,0,0,0,0,0,M
134884,1602166,5983,NaN,0,1,5.000000,5.000000,5.000000,NaN,NaN,...,NaN,NaN,NaN,8861,0,0,0,0,0,M
134886,1358362,38167,NaN,0,4,2.500000,3.250000,3.000000,2.250000,3.666667,...,NaN,NaN,NaN,6282,0,0,0,0,0,F
134888,1446020,113781,NaN,0,3,3.666667,3.666667,3.666667,3.666667,5.333333,...,NaN,NaN,NaN,3734,0,0,0,0,0,F
134889,810311,31606,NaN,0,5,5.000000,4.800000,4.800000,3.600000,0.000000,...,NaN,NaN,NaN,5238,0,0,0,0,0,F
134890,916966,2803112,NaN,0,1,1.000000,1.000000,1.000000,1.000000,NaN,...,NaN,NaN,NaN,4655,0,0,0,0,0,M
134895,1104196,3320288,NaN,0,1,1.000000,1.000000,2.000000,2.000000,NaN,...,NaN,NaN,NaN,2823,0,0,0,0,0,F
134899,588891,139413,NaN,0,3,3.666667,4.333333,2.333333,3.333333,2.333333,...,NaN,NaN,NaN,1435,0,0,0,0,0,M
134901,1366019,3292597,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,NaN,NaN,NaN,2731,0,0,0,0,0,M
134903,972082,645591,NaN,0,1,5.000000,5.000000,3.000000,5.000000,NaN,...,NaN,NaN,NaN,2389,0,0,0,0,0,M
134904,831680,615185,NaN,0,3,3.333333,4.333333,4.000000,2.666667,1.333333,...,NaN,NaN,NaN,6282,0,0,0,0,0,M
134905,1306491,185570,NaN,0,2,5.000000,5.000000,4.500000,5.000000,0.000000,...,NaN,NaN,NaN,1741,0,0,0,0,0,F
134910,188148,887382,NaN,0,2,1.000000,2.000000,2.000000,1.500000,0.000000,...,NaN,NaN,NaN,8073,0,0,0,0,0,M
134911,1239152,70358,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,NaN,NaN,NaN,9760,0,0,0,0,0,M
134924,879980,144573,NaN,0,4,3.750000,4.500000,3.750000,4.000000,1.583333,...,NaN,NaN,NaN,556,0,0,0,0,0,M
134925,1336864,2332013,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,NaN,NaN,NaN,5478,0,0,0,0,0,M
134935,868723,153368,NaN,0,2,2.500000,2.500000,3.000000,3.000000,0.500000,...,NaN,NaN,NaN,5862,0,0,0,0,0,M
134937,711194,164510,NaN,0,3,4.000000,4.000000,4.000000,3.666667,3.000000,...,NaN,NaN,NaN,3108,0,0,0,0,0,F
134942,211646,711526,NaN,0,2,5.000000,5.000000,5.000000,5.000000,0.000000,...,NaN,NaN,NaN,9189,0,0,0,0,0,M
134943,9685,20809,NaN,0,5,4.200000,4.800000,3.200000,1.800000,3.200000,...,NaN,NaN,NaN,9308,0,0,0,0,0,M
134952,1036394,2330978,NaN,0,1,1.000000,1.000000,3.000000,3.000000,NaN,...,NaN,NaN,NaN,1869,0,0,0,0,0,M
134960,425150,127715,NaN,0,1,3.000000,3.000000,3.000000,NaN,NaN,...,NaN,NaN,NaN,1602,0,0,0,0,0,M
134964,818326,168166,NaN,0,2,3.000000,3.000000,4.500000,3.500000,8.000000,...,NaN,NaN,NaN,5131,0,0,0,0,0,M
134969,1049044,3205133,NaN,0,3,2.666667,2.666667,3.000000,3.000000,4.333333,...,NaN,NaN,NaN,6282,0,0,0,0,0,F
134970,1132315,2880773,NaN,0,3,3.666667,4.333333,3.333333,4.333333,5.333333,...,NaN,NaN,NaN,6817,0,0,0,0,0,F

#### Convert the review corpus into a list of sentences

In [42]:
im_data.loc[:,['sentence']]= im_data['review_corpus'].map(lambda x: x.split('|'))

In [54]:
im_data['word'] = im_data['sentence'].map(lambda x: [word_tokenize(i) for i in x] )

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

#### Calculate number of reviews of each doctor

In [43]:
im_data.loc[:,['Number of Review']] = im_data['sentence'].map(lambda x: len(x))

#### Calculate average length of reviews of each doctor

In [68]:
def sum_words(x):
    words = 0
    for i in x:
        words = len(i)
    return words

In [69]:
im_data['averaeg length'] = im_data['word'].map(lambda x: sum_words(x)/len(x))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [72]:
im_data[['Number of Review','averaeg length']].head()

    Number of Review  averaeg length
2                 11       18.727273
6                  9       11.333333
14                10        3.300000
15                 1       57.000000
22                 2       16.000000

In [73]:
im_data

,hp_id,ratemds_id,order_id,hasorder,review_count,avg_help,avg_know,avg_punct,avg_staff,var_help,...,basecat_badmed,basecat_impaired,basecat_finances,basecat_criminal,basecat_patient,gender,sentence,Number of Review,word,averaeg length
2,19713,127113,NaN,0,11,2.272727,2.636364,3.000000,2.000000,3.218182,...,0,0,0,0,0,F,[satisfactory but would not recommend coldness...,11,"[[satisfactory, but, would, not, recommend, co...",18.727273
6,587845,31782,NaN,0,9,4.555556,4.555556,4.222222,2.444444,1.777778,...,0,0,0,0,0,M,[I have been going to Dr. Mittleman for the pa...,9,"[[I, have, been, going, to, Dr., Mittleman, fo...",11.333333
14,1026482,33127,NaN,0,10,4.600000,4.800000,4.800000,2.800000,1.600000,...,0,0,0,0,0,F,[What I like most about Dr. Brandies is that s...,10,"[[What, I, like, most, about, Dr., Brandies, i...",3.300000
15,356796,175423,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,0,0,0,0,0,F,[I have been a patient for 5+ years. She alway...,1,"[[I, have, been, a, patient, for, 5+, years, ....",57.000000
22,1444150,459077,NaN,0,2,5.000000,5.000000,5.000000,5.000000,0.000000,...,0,0,0,0,0,M,[Dr. Kloosterman was so kind and knowledgable!...,2,"[[Dr., Kloosterman, was, so, kind, and, knowle...",16.000000
23,1298609,754757,NaN,0,4,3.000000,3.750000,4.000000,3.500000,3.333333,...,0,0,0,0,0,M,[I no longer use this doctor he doesn't have t...,4,"[[I, no, longer, use, this, doctor, he, does, ...",2.750000
26,48453,841438,NaN,0,1,3.000000,1.000000,5.000000,4.000000,NaN,...,0,0,0,0,0,M,[This doctor brushed aside everything I said w...,1,"[[This, doctor, brushed, aside, everything, I,...",123.000000
27,1128956,1252,NaN,0,3,4.666667,4.666667,4.666667,3.333333,0.333333,...,0,0,0,0,0,M,"[good for pulmonary disease, but definitely no...",3,"[[good, for, pulmonary, disease, ,, but, defin...",0.666667
28,912294,94308,NaN,0,6,3.000000,3.333333,2.833333,1.333333,3.600000,...,0,0,0,0,0,M,"[So, the first thing this idiot does is argue ...",6,"[[So, ,, the, first, thing, this, idiot, does,...",12.833333
33,1529842,418509,NaN,0,1,3.000000,3.000000,2.000000,2.000000,NaN,...,0,0,0,0,0,M,[Deceased ],1,[[Deceased]],1.000000
37,874463,147822,NaN,0,1,5.000000,4.000000,4.000000,4.000000,NaN,...,0,0,0,0,0,F,[ ],1,[[]],0.000000
40,212783,399757,NaN,0,1,5.000000,5.000000,4.000000,4.000000,NaN,...,0,0,0,0,0,M,[Speedy service ],1,"[[Speedy, service]]",2.000000
41,945140,3323975,NaN,0,1,1.000000,2.000000,1.000000,2.000000,NaN,...,0,0,0,0,0,M,[Expect a minimum of a month to return a phone...,1,"[[Expect, a, minimum, of, a, month, to, return...",44.000000
52,406301,162169,2037974.0,1,1,1.000000,2.000000,3.000000,2.000000,NaN,...,0,0,0,0,0,M,[ ],1,[[]],0.000000
58,411960,1151070,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,0,0,0,0,0,M,[Dr. Mejia takes the time to review my file an...,1,"[[Dr., Mejia, takes, the, time, to, review, my...",101.000000
67,1525567,168134,NaN,0,1,1.000000,4.000000,4.000000,1.000000,NaN,...,0,0,0,0,0,M,[This physician is very rude to everyone. Pati...,1,"[[This, physician, is, very, rude, to, everyon...",28.000000
68,942069,18484,NaN,0,4,4.000000,4.250000,4.500000,1.250000,4.000000,...,0,0,0,0,0,M,[Jon Moness has been my doctor for the past 10...,4,"[[Jon, Moness, has, been, my, doctor, for, the...",15.000000
71,1215516,438858,NaN,0,4,2.250000,3.250000,3.500000,3.500000,3.583333,...,0,0,0,0,0,M,[He is a very smart doctor. But he has horribl...,4,"[[He, is, a, very, smart, doctor, ., But, he, ...",5.000000
75,1473699,123294,NaN,0,1,5.000000,5.000000,4.000000,4.000000,NaN,...,0,0,0,0,0,M,[Extremely intelligent ],1,"[[Extremely, intelligent]]",2.000000
84,1327850,21399,NaN,0,3,5.000000,5.000000,4.000000,1.666667,0.000000,...,0,0,0,0,0,F,[Wonderful Doc. She has been my pcp for years....,3,"[[Wonderful, Doc, ., She, has, been, my, pcp, ...",4.000000
85,1520937,165925,NaN,0,4,4.000000,4.000000,4.000000,4.000000,4.000000,...,0,0,0,0,0,M,[he is the best physician . very informative a...,4,"[[he, is, the, best, physician, ., very, infor...",0.000000
88,1054179,2626043,NaN,0,1,1.000000,1.000000,3.000000,1.000000,NaN,...,0,0,0,0,0,M,[This doctor acted as if I was a hypochondriac...,1,"[[This, doctor, acted, as, if, I, was, a, hypo...",211.000000
91,904721,865724,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,0,0,0,0,0,M,"[Great physician, very caring, extensive exper...",1,"[[Great, physician, ,, very, caring, ,, extens...",55.000000
94,275305,175595,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,0,0,0,0,0,M,[ ],1,[[]],0.000000
95,1488908,3258507,NaN,0,1,2.000000,2.000000,1.000000,3.000000,NaN,...,0,0,0,0,0,F,[Sees you with one foot out of the door. ],1,"[[Sees, you, with, one, foot, out, of, the, do...",10.000000
109,1608047,189982,NaN,0,1,5.000000,5.000000,5.000000,3.000000,NaN,...,0,0,0,0,0,F,[I would not see anyone but her. She takes the...,1,"[[I, would, not, see, anyone, but, her, ., She...",17.000000
118,269347,18985,NaN,0,7,3.000000,3.571429,3.714286,1.714286,4.000000,...,0,0,0,0,0,M,[Dr. Quinto gives the impression that unless y...,7,"[[Dr., Quinto, gives, the, impression, that, u...",8.714286
120,827768,3262839,NaN,0,1,1.000000,2.000000,3.000000,4.000000,NaN,...,0,0,0,0,0,M,[I went to this doctor for about 1 1/2 years w...,1,"[[I, went, to, this, doctor, for, about, 1, 1/...",102.000000
122,890406,121100,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,0,0,0,0,0,F,"[Dr. Kane provides highly expert, caring, and ...",1,"[[Dr., Kane, provides, highly, expert, ,, cari...",53.000000
123,1371705,124510,NaN,0,1,5.000000,5.000000,5.000000,NaN,NaN,...,0,0,0,0,0,M,"[Dr. Kuwata is very professional and caring,li...",1,"[[Dr., Kuwata, is, very, professional, and, ca...",19.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134857,1195114,247510,NaN,0,1,1.000000,1.000000,1.000000,1.000000,NaN,...,0,0,0,0,0,M,[MY MOTHER PASSED AWAY UNDER HIS CARE. HE IS T...,1,"[[MY, MOTHER, PASSED, AWAY, UNDER, HIS, CARE, ...",26.000000
134862,511759,171216,NaN,0,2,3.000000,3.000000,3.000000,3.000000,8.000000,...,0,0,0,0,0,M,[I went to this doctor for 3 years and got not...,2,"[[I, went, to, this, doctor, for, 3, years, an...",8.000000
134869,495256,142884,NaN,0,4,4.000000,4.500000,3.750000,3.500000,4.000000,...,0,0,0,0,0,M,[Did not tell my mother she should havae a col...,4,"[[Did, not, tell, my, mother, she, should, hav...",1.750000
134870,401038,643557,NaN,0,3,5.000000,5.000000,4.666667,5.000000,0.000000,...,0,0,0,0,0,F,[Without a doubt one of the best oncology team...,3,"[[Without, a, doubt, one, of, the, best, oncol...",3.000000
134880,88457,111288,NaN,0,2,3.000000,3.000000,4.000000,4.000000,8.000000,...,0,0,0,0,0,M,[I found Dr Corona to be currant on newest inf...,2,"[[I, found, Dr, Corona, to, be, currant, on, n...",67.500000
134882,1012083,208232,NaN,0,2,3.000000,3.000000,2.500000,2.500000,8.000000,...,0,0,0,0,0,M,[Bills insurance for the wrong diagnosis and d...,2,"[[Bills, insurance, for, the, wrong, diagnosis...",29.500000
134884,1602166,5983,NaN,0,1,5.000000,5.000000,5.000000,NaN,NaN,...,0,0,0,0,0,M,[He is friendly and caring. Always listens to ...,1,"[[He, is, friendly, and, caring, ., Always, li...",25.000000
134886,1358362,38167,NaN,0,4,2.500000,3.250000,3.000000,2.250000,3.666667,...,0,0,0,0,0,F,"[NOT impressed. Front office staff, unfriendly...",4,"[[NOT, impressed, ., Front, office, staff, ,, ...",3.500000
134888,1446020,113781,NaN,0,3,3.666667,3.666667,3.666667,3.666667,5.333333,...,0,0,0,0,0,F,[SHE IS A VERY GOOD DOCTOR. SHE WAS MY DOCTOR ...,3,"[[SHE, IS, A, VERY, GOOD, DOCTOR, ., SHE, WAS,...",10.666667
134889,810311,31606,NaN,0,5,5.000000,4.800000,4.800000,3.600000,0.000000,...,0,0,0,0,0,F,"[Dr. Silversmith is the nicest, caring, unders...",5,"[[Dr., Silversmith, is, the, nicest, ,, caring...",2.000000
134890,916966,2803112,NaN,0,1,1.000000,1.000000,1.000000,1.000000,NaN,...,0,0,0,0,0,M,[HORRIBLE! This doctor is from the army and st...,1,"[[HORRIBLE, !, This, doctor, is, from, the, ar...",23.000000
134895,1104196,3320288,NaN,0,1,1.000000,1.000000,2.000000,2.000000,NaN,...,0,0,0,0,0,F,"[Not a nice person. Very sharp, not very carin...",1,"[[Not, a, nice, person, ., Very, sharp, ,, not...",37.000000
134899,588891,139413,NaN,0,3,3.666667,4.333333,2.333333,3.333333,2.333333,...,0,0,0,0,0,M,[A visit with this doctor is not rushed. He is...,3,"[[A, visit, with, this, doctor, is, not, rushe...",19.666667
134901,1366019,3292597,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,0,0,0,0,0,M,[I have been a patient of Dr. Trock's since 20...,1,"[[I, have, been, a, patient, of, Dr., Trock, '...",213.000000
134903,972082,645591,NaN,0,1,5.000000,5.000000,3.000000,5.000000,NaN,...,0,0,0,0,0,M,[cares about everyone you can call and speek t...,1,"[[cares, about, everyone, you, can, call, and,...",75.000000
134904,831680,615185,NaN,0,3,3.333333,4.333333,4.000000,2.666667,1.333333,...,0,0,0,0,0,M,[I'd have to agree that Dr Uyesaka inspires co...,3,"[[I, 'd, have, to, agree, that, Dr, Uyesaka, i...",0.000000
134905,1306491,185570,NaN,0,2,5.000000,5.000000,4.500000,5.000000,0.000000,...,0,0,0,0,0,F,[Thank God for this doctor. She is super knowl...,2,"[[Thank, God, for, this, doctor, ., She, is, s...",12.000000
134910,188148,887382,NaN,0,2,1.000000,2.000000,2.000000,1.500000,0.000000,...,0,0,0,0,0,M,[My first experience with this doctor was when...,2,"[[My, first, experience, with, this, doctor, w...",44.000000
134911,1239152,70358,NaN,0,1,5.000000,5.000000,5.000000,5.000000,NaN,...,0,0,0,0,0,M,[Very Attentive ],1,"[[Very, Attentive]]",2.000000
134924,879980,144573,NaN,0,4,3.750000,4.500000,3.750000,4.000000,1.583333,...,0,0,0,0,0,M,[An excellent physician. A good diagnostician....,4,"[[An, excellent, physician, ., A, good, diagno...",4.250000
134925,1336864,2332013,NaN,0,1,5.000000,5.000000,4.000000,5.000000,NaN,...,0,0,0,0,0,M,"[Excellent doctor, in terms of skill, knowledg...",1,"[[Excellent, doctor, ,, in, terms, of, skill, ...",14.000000
134935,868723,153368,NaN,0,2,2.500000,2.500000,3.000000,3.000000,0.500000,...,0,0,0,0,0,M,[This doctor was unable to complete the colono...,2,"[[This, doctor, was, unable, to, complete, the...",0.000000
134937,711194,164510,NaN,0,3,4.000000,4.000000,4.000000,3.666667,3.000000,...,0,0,0,0,0,F,[best all time Dr. She takes care of my mother...,3,"[[best, all, time, Dr., She, takes, care, of, ...",29.666667
134942,211646,711526,NaN,0,2,5.000000,5.000000,5.000000,5.000000,0.000000,...,0,0,0,0,0,M,[Exquisite diagnostician! Dr. Myaing was the l...,2,"[[Exquisite, diagnostician, !, Dr., Myaing, wa...",23.500000
134943,9685,20809,NaN,0,5,4.200000,4.800000,3.200000,1.800000,3.200000,...,0,0,0,0,0,M,"[Dr. Rickles is helpful, informative and consi...",5,"[[Dr., Rickles, is, helpful, ,, informative, a...",14.800000
134952,1036394,2330978,NaN,0,1,1.000000,1.000000,3.000000,3.000000,NaN,...,0,0,0,0,0,M,[I was very disappointed with this doctor. He ...,1,"[[I, was, very, disappointed, with, this, doct...",104.000000
134960,425150,127715,NaN,0,1,3.000000,3.000000,3.000000,NaN,NaN,...,0,0,0,0,0,M,[Above average. Some room for improvement. ],1,"[[Above, average, ., Some, room, for, improvem...",8.000000
134964,818326,168166,NaN,0,2,3.000000,3.000000,4.500000,3.500000,8.000000,...,0,0,0,0,0,M,[Saw him several times for liver disease -- he...,2,"[[Saw, him, several, times, for, liver, diseas...",13.500000
134969,1049044,3205133,NaN,0,3,2.666667,2.666667,3.000000,3.000000,4.333333,...,0,0,0,0,0,F,"[dr. Foster has been excellent, she has hapled...",3,"[[dr., Foster, has, been, excellent, ,, she, h...",4.333333
134970,1132315,2880773,NaN,0,3,3.666667,4.333333,3.333333,4.333333,5.333333,...,0,0,0,0,0,F,[Dr. Davis is a very caring physician. She is ...,3,"[[Dr., Davis, is, a, very, caring, physician, ...",29.333333

In [74]:
im_data.to_csv("/Users/chongchen/Desktop/19Fall RA/Internal_Medicine_Summarize_Review.csv")